# Generated by Django 5.2 on 2025-05-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="etat_civil",
            field=models.CharField(
                choices=[
                    ("celibataire", "Célibataire"),
                    ("marie", "Marié(e)"),
                    ("divorce", "Divorcé(e)"),
                    ("veuf", "Veuf(ve)"),
                ],
                default="Unknown",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sexe",
            field=models.CharField(
                choices=[("homme", "Homme"), ("femme", "Femme")],
                default="Unknown",
                max_length=10,
            ),
        ),
    ]
