# Generated by Django 5.2 on 2025-05-22 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_etat_civil_alter_user_sexe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_embauche",
        ),
        migrations.AlterField(
            model_name="user",
            name="date_naissance",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="etat_civil",
            field=models.CharField(
                choices=[
                    ("celibataire", "Célibataire"),
                    ("marie", "Marié(e)"),
                    ("divorce", "Divorcé(e)"),
                    ("veuf", "Veuf(ve)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sexe",
            field=models.CharField(
                choices=[("homme", "Homme"), ("femme", "Femme")], max_length=10
            ),
        ),
    ]
