# Generated by Django 5.2 on 2025-05-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_date_embauche_alter_user_date_naissance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departement",
            name="postes",
        ),
        migrations.AddField(
            model_name="departement",
            name="postes",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="user.poste"
            ),
            preserve_default=False,
        ),
    ]
