# Generated by Django 5.2 on 2025-05-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_departement_postes_departement_postes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departement",
            name="postes",
        ),
        migrations.AddField(
            model_name="poste",
            name="departement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.departement",
            ),
            preserve_default=False,
        ),
    ]
