# Generated by Django 5.2 on 2025-05-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_departement_postes_poste_departement"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="taux_reactivite",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="taux_respect_delais",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
