# Generated by Django 5.2 on 2025-05-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_user_taux_reactivite_user_taux_respect_delais"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="taux_reactivite",
        ),
        migrations.RemoveField(
            model_name="user",
            name="taux_respect_delais",
        ),
    ]
