# Generated by Django 5.2 on 2025-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_user_taux_reactivite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("agent", "Agent"),
                ],
                max_length=10,
            ),
        ),
    ]
