# Generated by Django 5.2 on 2025-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("agent", "Agent"),
                ],
                default="agent",
                max_length=10,
            ),
        ),
    ]
