# Generated by Django 5.2 on 2025-05-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="departement",
            name="est_supprime",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="poste",
            name="est_supprime",
            field=models.BooleanField(default=False),
        ),
    ]
