# Generated by Django 5.2 on 2025-05-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_departement_est_supprime_poste_est_supprime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
