# Generated by Django 5.2 on 2025-05-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categorie",
            new_name="Projet",
        ),
    ]
