# Generated by Django 5.2 on 2025-05-22 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_rename_categorie_projet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="chef_projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projet",
            name="nom",
            field=models.CharField(max_length=255),
        ),
    ]
