# Generated by Django 5.2 on 2025-05-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_projet_chef_projet_projet_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tache",
            name="categorie",
        ),
        migrations.AddField(
            model_name="projet",
            name="tache",
            field=models.ManyToManyField(blank=True, null=True, to="task.tache"),
        ),
    ]
