# Generated by Django 5.2 on 2025-05-22 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_remove_tache_categorie_projet_tache"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projet",
            name="tache",
        ),
        migrations.AddField(
            model_name="tache",
            name="projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taches",
                to="task.projet",
            ),
        ),
    ]
