# Generated by Django 5.2 on 2025-05-23 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0006_alter_tache_assigne_par_alter_tache_projet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tache",
            name="assigne_par",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taches_attribuees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
