# Generated by Django 5.2 on 2025-05-23 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0007_alter_tache_assigne_par"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tache",
            name="assigne_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taches_attribuees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tache",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_retard", "En retard"),
                    ("en_cours", "En cours"),
                    ("terminee", "Terminée"),
                ],
                default="en_cours",
                max_length=20,
            ),
        ),
    ]
