# Generated by Django 5.2 on 2025-05-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_alter_tache_assigne_par_alter_tache_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="tache",
            name="nombre_jour_execution",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tache",
            name="nombre_jour_reel",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
