# Generated by Django 5.2 on 2025-05-28 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0010_alter_tache_assigne_par"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tache",
            name="assigne_a",
        ),
        migrations.AddField(
            model_name="tache",
            name="assigne_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taches_reçues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
