# Generated by Django 5.2 on 2025-05-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0011_remove_tache_assigne_a_tache_assigne_a"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="est_supprime",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tache",
            name="est_supprime",
            field=models.BooleanField(default=False),
        ),
    ]
